### ISSUE TITLE
Markdown formatting for "Bold" and "Italic" works inconsistently in a numbered or bulleted list

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#584] opened 2018-01-16 15:42 UTC
[Affected versions]:
- Firefox 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 2018/01/16) installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to a website, drag and drop some text into the Notes sidebar.
3. Organize the text in a numbered list that contains at least 3 items.
4. At the end of each item from the list, leave one blank space and type a word using the markdown formatting (see this [screenshot](https://screenshots.firefox.com/jtS1KQxQnOl4A1pP/medium.com)).
5. Press "Space" key and observe the appearance of the formatted words.

[Expected result]:
- The words are correctly formatted and displayed.

[Actual result]:
- The words lose their formatting, except the last item from the list.

[Notes]:
- Also, during testing I've encountered cases where only some words lost their formatting and other didn't.
- This issue is not reproducible for a numbered /bulleted list that contains short items (only 1-3 words).
- This issue is not reproducible if you paste text in the sidebar from text documents such as Notepad C++, LibreOffice etc.
- This issue is also reproducible with the Firefox Notes latest version from Test Pilot experiment [page](https://testpilot.firefox.com/experiments/notes).
- Here is a screen recording of the issue:
![markdown formatting inconsistency](https://user-images.githubusercontent.com/31244235/34995485-4c9b130a-fadf-11e7-8c94-2a0506aa4f8e.gif)

**Comment by Natim** [comment] 2018-01-18 09:42
@Mgsy Are you aware of that bug already?

**Comment by Mgsy** [comment] 2018-01-18 10:55
This is interesting, but unfortunately I'm not able to reproduce this issue. Checked in Firefox 57.0.4 on Windows 10 and OS X.

![bug_cke5](https://user-images.githubusercontent.com/20988892/35094676-42c949ba-fc46-11e7-8e7e-efd32a411413.gif)

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-18 14:22
Indeed this issue is tricky because as I've mentioned in the notes, during testing I've encountered cases where only some words lost their formatting options and some didn't.

@Mgsy, can you please try to format all the items from the numbered list? In this way, maybe you'll encounter this issue.

I've retested this using Firefox Notes from Test Pilot experiments [page](https://testpilot.firefox.com/experiments/notes) and managed to reproduce it on Windows 10 x64, on latest Firefox release 57.0.4. I've also reproduce it on https://ckeditor5.github.io/, as you can see in the below screen recording:
Firefox Notes:
![markdown formatting on notes test pilot](https://user-images.githubusercontent.com/31244235/35102279-2741b59a-fc6b-11e7-92d2-31ba6944726b.gif)
CKEditor 5:
![markdown formatting - ckeditor](https://user-images.githubusercontent.com/31244235/35102293-32777968-fc6b-11e7-9fdc-f22a964d4bd9.gif)

**Comment by Mgsy** [comment] 2018-01-19 08:24
@Softvision-CristinaBadescu, thanks for the detailed explanation. I'm trying to reproduce this issue, but unfortunately without success.

![bug_cke5](https://user-images.githubusercontent.com/20988892/35141035-c8c15e1e-fcf9-11e7-9292-9454aad484aa.gif)

I've tested it on Windows 10 x64 in Firefox 57.0.4, latest CKEditor 5 master. I've checked it also on https://ckeditor5.github.io. 

This is really interesting and I will be trying to figure out how to reproduce it and get exact steps to follow. If I find something, I will give you an update in this issue.

Just one question - do you have some addons installed in your Firefox? Or some settings which are not enabled by default (e.g. caret browsing mode)?

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-19 08:51
Hey @Mgsy , thanks for looking again into this. 
As I've watched carefully your screen recording I've noticed one difference: you have no blank space at the end of your sentence, before you start typing the word using the markdown formatting. 

I'm not sure, but this might be the reason why I've managed to reproduce it, because if I leave no blank space before using markdown formatting, I cannot reproduce it either :) Considering this, I'm going to update step 4.

**Comment by Mgsy** [comment] 2018-01-19 09:08
> As I've watched carefully your screen recording I've noticed one difference: you have no blank space at the end of your sentence, before you start typing the word using the markdown formatting.

Yep, I noticed that your text has blank space and checked this scenario either. Unfortunately without success, so I guess it's not the reason.

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-19 12:39
> Just one question - do you have some addons installed in your Firefox? Or some settings which are not enabled by default (e.g. caret browsing mode)?

No, I had no addons installed, and didn't changed the default settings, not even turning on the Caret Browsing. Only when I tested on Firefox Release, Test Pilot v2.0.6dev was installed along with Notes, from the experiments page.

**Comment by Mgsy** [comment] 2018-01-23 09:45
@Softvision-CristinaBadescu, I was trying to reproduce this issue and finally I made it. I've created new ticket in our CKEditor 5 repository, you can track it here - https://github.com/ckeditor/ckeditor5/issues/779. Thanks for your help!

**Comment by vladikoff** [comment] 2018-07-20 15:15
Still pending, work upstream...

**Comment by Mgsy** [comment] 2019-02-14 13:25
>Still pending, work upstream...

Hi, @vladikoff! I'm happy to announce that this bug is fixed on the latest version of CKEditor 5 🎉

**Comment by vladikoff** [comment] 2019-02-14 13:27
> Hi, @vladikoff! I'm happy to announce that this bug is fixed on the latest version of CKEditor 5 🎉

Woohoo!! Thank you!!

**Closed** 2023-01-06 11:56 UTC
Labels: enhancement, ckeditor, ARCHIVED
