### ISSUE TITLE
Markdown feedback

### ISSUE THREAD

**Issue by marniepw** [mozilla/notes#666] opened 2018-02-05 23:42 UTC
[Description]: 

1. I was writing some notes and tried writing wrote word1_word2_word3 and while writing it, it did word1word2word3 and word 2 was in italics.  I am assuming that's because of the underlines but I am not sure this is intentional behavior. Thanks!
2. There should be a way to disable Markdown. It's annoying to paste in text with single line breaks and have them all disappear.

[Affected versions]: Unknown; from January survey feedback.

[Prerequisites]:

[Steps to reproduce]:

[Expected result]:

[Actual result]:

[Additional Notes]:

**Comment by Natim** [comment] 2018-02-07 13:08
1. It is a duplicate of #595
2. To be honest I don't think this is related to Markdown but more a CKEditor bug related to #628

**Closed by Natim** 2018-02-07 13:08 UTC
