### ISSUE TITLE
The "View Selection Source" does not work

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#267] opened 2017-09-29 15:11 UTC
**[Affected versions]:**
- Firefox Notes 1.8.0dev
- Firefox 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Write a string in the "Notes" sidebar.
3. Select all content and right click.
4. Click  the "View Selection Source" option and observe the browser behavior.

**[Expected result]:**
- Another tab is opened and the source of the selection is displayed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- Attached a screen recording of the issue:
![view source selection](https://user-images.githubusercontent.com/31243259/31022433-72cc387c-a541-11e7-949f-c7d7dc8c8b18.gif)

**Comment by Natim** [comment] 2017-09-29 15:12
Please file a Firefox bug in bugzilla for this one.

**Comment by Softvision-MariusComan** [comment] 2017-09-29 15:26
@Natim, [here it is](https://bugzilla.mozilla.org/show_bug.cgi?id=1404367).

**Comment by Natim** [comment] 2018-01-10 11:05
The issue is handled on the bugzilla side. I am closing it here.

**Closed by Natim** 2018-01-10 11:05 UTC
Labels: Firefox Bug
