### ISSUE TITLE
Link a note to a certain URL or to a domain

### ISSUE THREAD

**Issue by klint** [mozilla/notes#242] opened 2017-09-20 14:44 UTC
I can't imagine a Note-taking tool on a browser without the ability to link a note to a certain page (URL or upper level up to the domain), like good old ATNotes that is no longer maintained. :)
And displaying this page would display all notes related to it.
These are the basic features, but other like search on *all* notes will also be helpful.
Thanks

**Comment by Natim** [comment] 2017-09-20 14:51
Duplicate of #233

**Comment by Natim** [comment] 2017-09-20 14:51
Actually not

**Comment by kpuljek** [comment] 2017-09-21 13:32
I believe this could fit under #40

**Comment by johngruen** [comment] 2017-09-21 15:22
Let's keep this open for now. We've been doing explorations in this area

**Comment by kpuljek** [comment] 2017-09-21 15:38
Would that also include a context menu option to "save selected text as a new note"? :)

**Comment by MiltonAkash** [comment] 2017-09-29 12:10
https://github.com/mozilla/notes/pull/264

**Comment by kpuljek** [comment] 2017-09-29 12:18
@MiltonAkash great feature, but this one is different - it's not for adding links to notes but attaching some notes to specific websites. Like if I go to ubuntu.com and make a note there, it would be visible when I visit that site, or if I browse through my notes it would state that it's linked to ubuntu.com.

**Comment by MiltonAkash** [comment] 2017-09-29 12:19
okk

**Comment by adrm** [comment] 2018-01-14 15:46
Yes, I expected the product would behave in this way. I would like it to. It's not really useful for me as a single note.

**Comment by a2sheppy** [comment] 2018-06-21 21:12
Agreed that having per-domain notes would be much more useful in many cases. Yeah, having global notes (a to-do list or whatever) would be nice, but being able to associate a note with a given page or domain would be much more handy. I could then use it to keep notes on things I need to fix on a given article, blog post, or google doc (per-page), or to keep notes about products that interest me as I shop on Amazon (per-domain), while I have a global note that has a to-do list reminding me to do my shopping and finish working on my article.

**Comment by skierpage** [comment] 2019-09-09 23:44
This add-on's description "Displays a sidebar that lets you take notes on web pages" made me hope it already works this way.

The do-it-yourself approach is the user copies the URL of the web page into the note so she can later search through notes to find the one for its URL.

The partly automated approach is when you create a new note the add-on always copies in the URL of the page you're on, and then there's a way while browsing to have the add-on search for notes approximately matching the current web page's URL.

Better: Add an explicit Attach button "Attach this note to current web page" that establishes the connection.
* Visiting the web page loads its attached note, if any. (Probably should disallow multiple notes per URL, which complicates Attach logic & UI).
* When you view a note that's attached, provide affordance to go to that page. (Probably should disallow attaching one note to more than one URL.)
* Need a way to detach a note in order to return it to being a general note and also to reattach it to a better URL.

You need a way to edit the URL to which the note is attached, but rather than rebuild Firefox's location field inside the add-on, I think expert users can just detach the note, edit the web page's URL, and attach again.

The hardest part may be doing the right thing to determine the same "page" URL. If you revisit a web page with insanely long tracking parameters on its URL, Notes for Firefox should still load the attached note; ideally when you attach it ignores those same tracking parameters, but not `?topic=1584&page=7` content parameters; sometimes the `#` fragment identifier is just different sections of a page but in a single-page app it displays completely different text. Hmmm. Expert users can detach, tweak the URL, then reattach; but less expert users could wind up with multiple notes on variations of the "same" web page and conversely keep seeing the same note for "different" web pages.

Sorry to blather. Thanks for your work!

**Closed** 2023-01-06 11:56 UTC
Labels: Links, webextension 💻, ARCHIVED
