### ISSUE TITLE
The shortcut for Strikethrough option doesn't work if there is no selected text

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#381] opened 2017-11-02 17:21 UTC
[Affected versions]:
- Firefox 56.0.2 and up
- Notes 1.9.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Notes experiment (1.9.0dev built on 11/02/2017) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Focus the editing area of Notes Sidebar.
3. Press "Ctrl"+"Shift"+"X" keys and observe what happens next.

[Expected result]:
- Strikethrough option is highlighted and selected.

[Actual result]:
- Strikethrough option is not highlighted nor selected.

[Notes]:
- The other shortcuts work as expected.
- Attached a screen recording of the issue:

![strokethrough shortcut](https://user-images.githubusercontent.com/26000308/32340208-a10330a2-c002-11e7-906e-ba50b319bf14.gif)

**Comment by Natim** [comment] 2018-02-02 14:30
I believe this is a duplicate of #402

**Closed by Natim** 2018-02-02 14:30 UTC
Labels: ckeditor
