### ISSUE TITLE
Welcome message not getting erased as soon as user tries to enter/type any text into Notes

### ISSUE THREAD

**Issue by Radhraj** [mozilla/notes#198] opened 2017-08-10 18:14 UTC
Steps to reproduce:
1.	Open the browser which has Notes plugin enabled
2.	Click on Notes.
3.	Start typing any text.

Expected Result:
The Welcome message must get erased

Actual Result:
Welcome message is not getting erased.

Attached Screenshot:
![welcomemessagenoterased](https://user-images.githubusercontent.com/30893077/29185078-d2f1c0e8-7e25-11e7-8f5c-d5f0a0935f5a.gif)

**Comment by cedricium** [comment] 2017-08-10 18:17
I'm not sure if the welcome message is actually supposed to get erased. 

@Natim @vladikoff Thoughts?

**Comment by Natim** [comment] 2017-08-11 08:19
It is note but I would understand why @Radhraj could expect it to be :)

**Comment by Sudeepa14** [comment] 2017-08-14 06:40
Hi , @Natim I would like to work on this future-request. Is that OK?

**Comment by vladikoff** [comment] 2017-08-14 12:56
@Sudeepa14 We are not sure if we want to actually do this. The existing note is meant to teach the user that text is editable, etc

**Comment by johngruen** [comment] 2017-08-14 15:10
yeah, this is a wontfix, since we have a separate placeholder. This is intended as intro text to let the user know that the field is editable.

**Closed by johngruen** 2017-08-14 15:10 UTC
Labels: Feature Request

**Comment by Sudeepa14** [comment] 2017-08-14 16:00
@vladikoff , @johngruen  Opz I already sent a PR with the requested functionality!  :) . Anyway It was fun working on the project! Thanks for the response!

**Comment by vladikoff** [comment] 2017-08-14 16:10
@Sudeepa14 yea sorry, I guess we didn't mean "Feature Request" to mean that we are going to build it.

**Comment by vladikoff** [comment] 2017-08-14 16:12
@Sudeepa14 some "confirmed" issues that we need to fix are in the `Next` milestone: https://github.com/mozilla/notes/issues?q=is%3Aopen+is%3Aissue+milestone%3ANext
