### ISSUE TITLE
The "Send to Notes" context menu option no longer works on the latest Beta and Nightly

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#832] opened 2018-03-28 16:06 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1449614

**[Affected versions]:**
- Firefox Beta (60.0b3) and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 3) installed.
- The "Firefox Notes" sidebar is opened in the list view mode.
- Have any website opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Select any text from the opened website and right click on it.
3. Click the "Send to Notes" option and observe the behavior.

**[Expected result]:**
- The selected text is displayed in the sidebar in a new note.

**[Actual result]:**
- The sidebar flickers and the selected text is not added as a new note.

**[Regression window]:**
Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
INFO: Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=7433031c9274b8299c3e2d50613de74352684bc1&tochange=95a6bd5b90452da6eee11eb8ee53ef80c91565c6

**[Additional Notes]:**
- If a note is opened when the "Send to Notes" context menu option is clicked, the sidebar goes back in the list view mode. In this case the text should have been added to the opened note.
- If the sidebar is closed when the "Send to Notes" context menu option is selected, the sidebar is opened in the list view mode. In this case the selected text should have been added as a new note.
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38041668-0c158bda-32bb-11e8-9f84-55d0cbb660eb.gif)

**Comment by vladikoff** [comment] 2018-03-28 16:12
@Softvision-MariusComan I'm super confused because this was supposed to be fixed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1445080

Ref: https://github.com/mozilla/notes/issues/740

**Comment by mixedpuppy** [comment] 2018-03-30 15:24
A change in notes 4 is that:

- it loads /sidebar/index.html, 
- changes the url to /sidebar/index.html#/
- when you use the context menu it loads /sidebar/index.html.  

Since the last no longer matches, a forced reload occurs.

The real fix should be to rely on the connected status.  I've provided a patch that fixes notes4

https://gist.github.com/mixedpuppy/61bfc082fff115c851ea5449d2c6343f

**Comment by vladikoff** [comment] 2018-03-30 15:39
thank you @mixedpuppy

**Comment by vladikoff** [comment] 2018-03-31 15:35
@mixedpuppy @sebastienbarbier I submit a PR here https://github.com/mozilla/notes/pull/857

However it is not working well.
![n](https://user-images.githubusercontent.com/128755/38164773-6eb32efa-34d7-11e8-8f72-c8151dad827f.gif)

We have behaviour where if you are in the Notes LIST then it should create a new note from selection, if you have a Note Open then it should add to it. 

@sebastienbarbier if you have time can you see if you can reproduce the router issues?

**Comment by vladikoff** [comment] 2018-03-31 15:35
We could also consider pulling this feature out of v4 due to instability

**Comment by vladikoff** [comment] 2018-03-31 16:07
@sebastienbarbier fyi you have to start the thing with ` npx web-ext run -s build  --firefox=nightly` (make sure it is nightly to see broken behaviour)

**Comment by sebastienbarbier** [comment] 2018-04-02 03:49
Should be good, pushed a fix in PR can you test and review ?

**Closed** 2018-04-03 02:36 UTC
Labels: Firefox Bug

**Comment by Softvision-MariusComan** [comment] 2018-04-03 08:59
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 6 build) installed, on the latest Firefox Release and Nightly. Verified on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
