### ISSUE TITLE
[Windows] "Notes" UI elements and content are zoomed in/out when holding the "Ctrl" key down and scrolling up/down using the mouse wheel

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#163] opened 2017-07-20 13:35 UTC
[Affected versions]:
- Firefox 56.0a1, Build ID: 20170719030206
- Firefox Notes dev v1.5.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.5.1 -dev, built on 07/20/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Hover the "Notes" sidebar.
3. Holding the "Ctrl" key down, scroll up/down using the mouse wheel.
4. Observe the "Notes" UI elements and content.

[Expected result]:
- The "Notes" UI elements and content doesn't suffer any changes.

[Actual result]:
- The "Notes" UI elements and content are zoomed in/out.

[Regression]:
With Nightly 56.0a1, Build ID: 20170710030203, the issue is not reproducible.
Last good revision: 392ed89ec2730a48d10b1cec741e86a242d28aa3
First bad revision: a625a2e9b3333a8e76982ea65f077cfded6ac224
Pushlog: https://goo.gl/e9m7Ei

[Notes]:
- Attached a screen recording of the issue:
![notes_ctrl_scrolling](https://user-images.githubusercontent.com/20083658/28419925-359e31c2-6d69-11e7-8c8b-e07c88fae929.gif)

**Comment by SoftVision-EmilPasca** [comment] 2017-07-20 13:48
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1382659

**Comment by Natim** [comment] 2017-07-20 13:57
My guess is that it is not a bug but a feature 💃

**Comment by cedricium** [comment] 2017-07-20 17:29
Yep, not actually a bug: https://science.house.gov/accessibility

> In most browsers, you can easily change the text size by zooming in and out with either your keyboard or the keyboard and a scroll wheel mouse.
>  - Zoom in - Hold down the Control (Ctrl) or Command (⌘) key and the plus (+) key.  If using a scroll wheel mouse, scroll while holding the Control or Command key down.
> - Zoom out - Hold down the Control (Ctrl) or Command (⌘) key and the minus (-) key.  If using a scroll wheel mouse, scroll while holding the Control or Command key down.
> - Zoom Reset - To change your zoom level back to the original setting, Hold down the Control (Ctrl) or Command (⌘) key and the zero (0).

**Comment by SoftVision-EmilPasca** [comment] 2017-07-21 09:19
If this is to be considered a feature, the following actions should be taken into account:

- The zoom should only apply to the sidebar content and not formatting option buttons ("Text Size","Bold","Italic", etc.)

- The zoom level of the sidebar cannot be actioned by keyboard shortcuts "Ctrl +/-" to zoom in/out and "Ctrl+0" to reset the zoom level.
 Instead, if the sidebar is focused and the CTRL +/- combination is pressed then the zoom is applied to the page.
 
- Both the mentioned and the aforementioned scenarios are only possible on Windows with the latest Nightly, on Beta and Release channels this is not possible. Moreover, on Mac OS the zoom level of the sidebar cannot be actioned at all.
Shouldn't this be possible on all platforms?

**Comment by Natim** [comment] 2018-01-10 11:10
I cannot reproduce it anymore so closing.

**Closed by Natim** 2018-01-10 11:10 UTC
Labels: Firefox Bug

**Comment by Saavestro** [comment] 2019-05-08 02:07
I like this feature but I would like to keep the same zoom level every time I open the side bar. I use linux and I get the default zoom level when I reopen the sidebar.
