### ISSUE TITLE
After removing Firefox Notes, the "Show sidebars" button is still displayed in the browser toolbar

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#76] opened 2017-06-16 13:25 UTC
[Notes]:
- The same behavior can be observed also when disabling the "Firefox Notes" add-on.
- Since by default you don't have the "Show sidebars" button in the browser toolbar, it would be better if the button will be moved back after removing/disabling Firefox Notes.

[Affected versions]:
- Firefox 53.0 and up
- Firefox Notes v1.2

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Notes add-on version (1.2 -dev, built on 16/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to "about:addons" and click on "Extensions".
3. Remove "Firefox Notes" add-on and observe the browser toolbar.

[Expected result]:
- The "Show sidebars" button is no longer displayed in the browser toolbar.

[Actual result]:
- The "Show sidebars" button is still displayed in the browser toolbar.

[Additional Notes]:
- Attached a screen recording of the issue:
![notes_toolbar_button](https://user-images.githubusercontent.com/20083658/27228431-4b4e70aa-52b0-11e7-8838-ef64d529bbc8.gif)

**Comment by vladikoff** [comment] 2017-06-16 13:40
@SoftVision-EmilPasca Good find! This is something that Firefox does.

cc @ryanfeeley check it out ^

**Comment by ryanfeeley** [comment] 2017-06-17 01:57
I'm not too bothered by this. The new sidebar switcher makes sidebars a lot more usable. And we're adding an "Open Tabs" sidebar soon (replacing Synced Tabs)

**Comment by vladikoff** [comment] 2017-06-19 17:48
Thanks for the bug @SoftVision-EmilPasca , @ryanfeeley will file a Firefox bug if this is not the desired behaviour.

Closing for now as it is "by design"

**Closed by vladikoff** 2017-06-19 17:48 UTC
