### ISSUE TITLE
Dragging and dropping Text into editor doesn't happen according to the cursor position

### ISSUE THREAD

**Issue by himanish-star** [mozilla/notes#552] opened 2018-01-06 11:22 UTC
**Expected**: When we drag and drop text into the editor then it should drop the text exactly at the position where the cursor is . 

**Actual**: When we drag and drop text into the editor then it drops the text according to the previous position of the cursor inside the editor

The GIF below explains this

![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/30361728/34639215-4e19667c-f301-11e7-8a21-c71fcc58d711.gif)

 1. My cursor position within the editor is after **Hel**. But I want to drop my text after **simple.** but the text gets dropped after **Hel**
 2. Then I have my cursor position after  **simple.**. But I want to drop my text after **intern** , but the text gets dropped after **simple.**

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-08 08:37
Thanks for reporting this issue. However, this is a dupe of #532.

**Closed by Softvision-CristinaBadescu** 2018-01-08 08:37 UTC

**Comment by himanish-star** [comment] 2018-01-08 09:16
@Softvision-CristinaBadescu , sorry for the inconvenience caused.
