### ISSUE TITLE
At first attempt cannot remove the add-on from the "about:addons" details page

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#545] opened 2018-01-04 09:11 UTC
[Notes]:
- Sometimes, at first add-on install, the theme options ("Default" and "Dark") might not appear and you need to refresh the "about:addons" page to see them.
- This issue is not reproducible when you select "Remove" button from "about:addons" main page.
- This issue is also reproducible after you use "Undo" option.

[Affected versions]:
- Firefox 57.0.3 and up

[Affected Platforms]:
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version installed from Test Pilot experiment page (https://testpilot.firefox.com/experiments/notes).

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to "about:addons" page and select "Extensions" section.
3. Click on "More" link and select the "Remove" button.
4. Observe the behavior.

[Expected result]:
- The add-on is removed.

[Actual result]:
- The add-on is not removed and the Theme options disappear.

[Additional notes]:
- This issue is also reproducible with the latest Firefox "Notes" add-on version (2.2.0dev custom build from 01.04.2018) installed.
- Here is a screen recording of the issue:
  
![remove add-on](https://user-images.githubusercontent.com/31244235/34556607-a5b1fcaa-f13f-11e7-866f-00c8974e5ce9.gif)

**Comment by Natim** [comment] 2018-01-04 09:18
Hello Cristina, thanks for this bug and the steps to reproduce it.
Can I ask you to also create a Bugzilla issue for this one since it is part of the Add-ons Management console ?

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-04 09:41
Hey Natim :) Sure thing, I've filled it here: bug [1427991](https://bugzilla.mozilla.org/show_bug.cgi?id=1427991).

**Comment by Natim** [comment] 2018-01-05 09:16
The bug has been identified by Firefox developers and a fix is coming up in the Bug, thanks :)

**Comment by Natim** [comment] 2018-01-09 14:28
I will close this bug since it is handled on the bugzilla side. Close to be landed.

**Closed by Natim** 2018-01-09 14:28 UTC
Labels: Firefox Bug
