### ISSUE TITLE
The content's font size is wrongly reseted after bullets / numbers are applied

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#430] opened 2017-11-22 16:51 UTC
**[Notes]:**
- A similar behavior is encountered when you have a Bulleted / Numbered list and you change the content's font size. After that the bullets / numbers are erased.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0dev custom built on 11.22.2017) installed.
- Have text in the "Firefox Notes" sized with H1, H2 or H3 font size.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and select all the content.
2. Press the "Bulleted List" button from the sidebar's toolbar and observe the behavior.

**[Expected result]:**
- The bullet is applied and the font size is unchanged. 

**[Actual result]:**
- The bullet is applied, but the font size is reset to "Paragraph".

**[Additional Notes]:**
- The issue is also reproducible with the "Numbered list".
- The issue in not reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33139504-28be70e8-cfb6-11e7-815f-7a5e30678bdd.gif)

**Comment by vladikoff** [comment] 2017-11-22 16:53
@ryanfeeley thoughts on this? By design?

**Comment by ryanfeeley** [comment] 2017-11-22 21:18
As designed.

**Comment by SoftVision-PaulOiegas** [comment] 2017-11-23 09:06
@vladikoff @ryanfeeley I can agree with this resolution if you guys can show me a known web application that behaves the same. Honestly, I have never seen one that behaves like this, that's why I encouraged Marius to log this issue found.

I'm looking right now at Thunderbird new email text box, GitHub comment boxes and Google Docs and they all support the behavior we were expecting for Notes too. So either I'm unfamiliar with text editor normal behaviors, or this is a still a valid issue.

**Comment by Natim** [comment] 2018-01-25 08:47
@SoftVision-PaulOiegas try to do it with a Github comment for instance. All Markdown based application behave like that for the sake of simplicity

**Comment by Natim** [comment] 2018-01-25 13:59
- ## test

**Comment by Natim** [comment] 2018-01-25 14:00
It actually works with Github

**Comment by Natim** [comment] 2018-01-25 14:01
@Reinmar are you already tracking this bug in CKEditor5?

**Comment by Reinmar** [comment] 2018-01-25 14:26
This is not a bug. This is how it's supposed to work with the current set of features. These formats are exclusive – something's either a list item or a paragraph or a heading. You can't have a heading list item in the current implementation of the list feature. The reason why it works this way is the content semantics. It's not a visual editor like MS Word where things like this might make sense.

Blocks like headings or block quotes, etc. make sense only in something that we call "document lists". For us, this is a separate feature. We don't know how it's going to work yet because the UX is a big problem there. We need to understand whether the user will be switching between those kinds of lists intentionally, or without their consciousness or whether this will be decided by the developer and the user won't have a choice. You can read more about this in https://github.com/ckeditor/ckeditor5-list/issues/47.

**Comment by ryanfeeley** [comment] 2018-01-25 15:29
Agreed, this is why I gave up on font size, because it actually worked more like headings. A shame that GitHub doesn't open source their editor. It's pretty good, although I think the WYSIWYG of CKEditor works best for most users in the context of Notes in the sidebar.

**Comment by Natim** [comment] 2018-01-25 15:30
I am going to close this bug then and we will follow up in ckeditor/ckeditor5-list#47.

**Closed** 2018-01-25 15:32 UTC
Labels: CKEditor Bug, ckeditor, enhancement
