### ISSUE TITLE
Should I get disconnected from Notes if I change/reset my FxA password?

### ISSUE THREAD

**Issue by rfk** [mozilla/notes#12] opened 2017-06-08 05:10 UTC
If the account password gets reset, the encryption keys will need to change, so ISTM it makes sense for any connected Notes clients to get disconnected straight away.  Does it also make sense to disconnect on password change?  IIRC that's the current behaviour for sync, all devices get disconnected on password change or reset.

**Comment by ryanfeeley** [comment] 2017-06-15 20:28
Yes, as soon as possible. State is designed (last on right) https://mozilla.invisionapp.com/share/6VBUYHMRB#/235284916_Desktop_Sidebar

**Comment by Natim** [comment] 2017-06-16 09:20
Today the behavior is that if the bearer token cannot connect to kinto, we disconnect the user.
Is that sufficient?

**Comment by vladikoff** [comment] 2017-06-16 10:59
@Natim we were discussing a feature where the tokens would get invalidated when password changes for certain clients (like this one). That might fix it 👍

**Comment by vladikoff** [comment] 2017-06-19 15:13
from mtg: Invalidate bearer tokens for this type of applications / clients OR find another way

**Comment by Natim** [comment] 2017-06-19 15:14
The issue is to make sure we detect if the keys is not valid anymore.

**Comment by rfk** [comment] 2017-06-20 03:09
My strawman proposal for handling this is two-fold.

First, on the FxA side, we arrange for password changes and resets to invalidate the OAuth tokens used by Firefox Notes.  If you check the OAuth token on every access, then you should immediately detect when there's been such an event, and should never find yourself using stale keys.

But of course, you will probably want to cache the OAuth token checks for performance reasons, so we need a backup plan for detecting when keys have changed.

Whenever you get a key via the FxA OAuth flow, it will have a "kid" property giving an opaque identifier for the key.  I suggest storing this somewhere alongside the encrypted data and checking that you're using the right key during each attempt to write new encrypted data.  It would be similar to the "X-Client-State" mechanism used in sync [1], although we should chat about cleaning up some of the details.

[1] https://mozilla-services.readthedocs.io/en/latest/token/apis.html#request-headers

**Comment by Natim** [comment] 2017-06-27 19:58
After talking about it this morning:

- Each time you verify a token (that also asked for keys) you will retrieve a kid.
- This kid should be stored along with the cache
- When a new token is validated and the kid changes, we invalidate all bearer token in the cache that are having this kid (so that their validation will fail later)
- Then it is impossible to authenticate on Kinto with a bearer linked to wrong keys, which will enforce people to reconnect.

In the meantime, clients won't be able to refresh their access token with a token generated before the keys reset.

**Comment by Natim** [comment] 2017-10-10 12:17
Duplicate of #111

**Closed by Natim** 2017-10-10 12:17 UTC
