### ISSUE TITLE
Numbered List / Bulleted List issue when you change Font

### ISSUE THREAD

**Issue by NikolayBG** [mozilla/notes#607] opened 2018-01-23 20:51 UTC
The problem is that when you create Numbered List and start taking notes land then decide to change the font it automatically stops counting and removes the number in front. 

Those are the steps:

1. Start a Numbered List
2. Write 1. test1, next row
3. test 2 and now mark the test 2 and switch the font to H3
4. Automatically stops the counter and removes the number in front

Comment: In MS Word it doesn't work like this. I don't know the requirements but for me it will be better if it doesn't stop counting and doesn't remove the number in front.

Regards,
Nikolay

**Comment by Natim** [comment] 2018-01-24 09:41
You are right, you can use bold but you cannot use a title inside a list.

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-25 08:46
Thanks for reporting this. However, this is a dupe of #430.

**Closed by Softvision-CristinaBadescu** 2018-01-25 08:46 UTC
