### ISSUE TITLE
Scroll bar cannot be grabbed and dragged

### ISSUE THREAD

**Issue by marniepw** [mozilla/notes#663] opened 2018-02-05 23:31 UTC
[Description]: The scroll bar was refusing to scroll by dragging, so I had to use my mouse's scroll wheel to scroll down.

[Affected versions]: Unknown; feedback is from January survey.

[Prerequisites]:

[Steps to reproduce]:

[Expected result]: Scrolling up and down with a mouse shall move the visible field of the note.

[Actual result]: Nothing happened.

[Additional Notes]:

**Comment by Natim** [comment] 2018-02-07 13:23
I couldn't reproduce this on Linux @SoftVision-EmilPasca can you try it on MacOS and Windows for the last version of notes?

**Comment by vladikoff** [comment] 2018-02-07 15:11
I saw scrollbar issues in Nightly, maybe that's why.

**Comment by vladikoff** [comment] 2018-02-07 15:11
I wonder if we should just hide the survey button in Nightly    /o\

**Comment by SoftVision-EmilPasca** [comment] 2018-02-07 15:28
I haven't managed to reproduce this with the latest Notes (2.2.0rc6), on Windows 10 x64 and Mac 10.12 using the latest Firefox Release (58.0.1), Dev Editions(59.0b4 -20180125163041) and latest Nightly (60.0a1-20180207100355).

**Comment by vladikoff** [comment] 2018-02-12 16:25
from mtg: closing for now

**Comment by Softvision-CristinaBadescu** [comment] 2018-03-08 10:06
I've managed to reproduce intermittently this issue (8 times out of 10), only on latest Firefox Release 58.0.2 and latest Firefox Beta 59.0, using Firefox Notes v3.0.0, on Windows 10 x64, by following the below steps:

1. Open Firefox browser, navigate to "https://testpilot.firefox.com/experiments/notes/" page and install the add-on.
2. Click and drag the scrollbar.

Also, I've noticed that if you navigate to "about:config" or "about:support" page, this issue doesn't occur anymore.

This issue is not reproducible on Arch Linux 4.12 and Mac 10.13.3.

Here is a screen recording with the issue:
![notes - cannot drag scrollbar -](https://user-images.githubusercontent.com/31244235/37145145-ccaa153a-22c8-11e8-970f-bc4fb9ec20be.gif)

**Closed** 2023-01-06 11:56 UTC
Labels: question, ARCHIVED
