### ISSUE TITLE
The "Delete" option from the context menu does not work if all the content is selected

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#485] opened 2017-12-06 15:13 UTC
**[Notes]:**
- The issue is reproducible only if the content is selected by pressing "Ctrl+A" or by using the "Select All" option from the context menu.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b8) installed.
- Have content in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Focus the sidebar and press "Ctrl+A".
3. Click the "Delete" option from the context menu and observe the behavior.

**[Expected result]:**
- All the content is deleted.

**[Actual result]:**
- The content is not deleted and an extra row is inserted in the top of the content area. 

**[Additional Notes]:**
- Also, after following the steps, the text caret is moved at the beginning of the content area and the formatting buttons from the toolbar are greyed-out.
- The issue is not reproducible if the content is selected using mouse drag.
- The issue is not reproducible if you press the "Delete" key instead.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33668531-b1d1371a-daa8-11e7-9538-9d0d82bdcfbd.gif)

**Comment by vladikoff** [comment] 2017-12-06 15:58
Duplicate of https://github.com/mozilla/notes/issues/423

**Closed by vladikoff** 2017-12-06 15:58 UTC
