### ISSUE TITLE
The sidebar is no longer displayed in a new window if it is opened from the "Firefox Notes" sign-in window

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#326] opened 2017-10-17 09:04 UTC
**[Affected versions]:**
- Firefox Notes 2.0.0a4
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0a4) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Click the "Sync Your Notes" button from the bottom-right part of the sidebar.
3. Open a new window (Ctrl/Cmd+N) and observe the displayed elements.

**[Expected result]:**
- The "Firefox Notes" sidebar is displayed.

**[Actual result]:**
- The "Firefox Notes" sidebar is not displayed.

**[Notes]:**
- Attached a screen recording of the issue:
![issue](https://user-images.githubusercontent.com/31243259/31656053-3f360b0a-b333-11e7-9850-2d86d4ea5162.gif)

**Comment by Natim** [comment] 2018-01-10 10:49
I am going to close this bug. It seems to me that since the sidebar was closed in the windows you opened the new windows it is the expected behaviour. Feel free to file a bugzilla issue if you want.

**Closed by Natim** 2018-01-10 10:49 UTC
Labels: Firefox Bug
