### ISSUE TITLE
Pressing "Tab" key continuously doesn't push the text on the next row if the text was previously numbered (or bulleted) listed

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#265] opened 2017-09-29 13:16 UTC
[Affected versions]:
- Firefox Notes 1.8.0dev
- Firefox 55.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" version (1.8.0dev) installed.

[Steps to reproduce]:
1. Open the browser with the profiles from prerequisites.
2. Write something in the editable area of Notes Sidebar.
3. Click on Numbered List (or Bulleted List) button.
4. Click on the area between the first letter of the text and the number (or bulleted) formatting option.
5. Press "Tab" key for at least 6 times and observe what happens with the text.

[Expected result]:
- The text along the formatting option chose at step 3 are moved to the right side until they reach the end of the row. After that, they are pushed down at the beginning of a new row.

[Actual result]:
- The text letters along the formatting option are displayed one on a row and the editable area is wrongly expanded on the horizontal.

[Notes]:
- This issue is not reproducible using the other formatting options.
- Attached a screen recording of the issue:

![tab](https://user-images.githubusercontent.com/26000308/31017329-bdf65faa-a530-11e7-8c35-39cfca9e24f0.gif)

**Comment by Natim** [comment] 2017-09-29 15:16
I am not sure I understand the expected behaviour here. Since you have the horizontal scrollbar and you can resize the scrollbar it doesn't looks to be a bug to me.

**Comment by johngruen** [comment] 2017-10-10 14:25
Can we set a max-depth on lists? otherwise this is a wontfix for me.

**Comment by Natim** [comment] 2017-10-10 14:31
I opened an upstream bug: https://github.com/quilljs/quill/issues/1753

**Comment by Natim** [comment] 2017-10-10 14:32
I opened a stackoverflow question to see if there is a nice way to set a max-depth option: https://stackoverflow.com/questions/46669374/is-there-a-way-to-define-a-max-list-depth

**Comment by Natim** [comment] 2017-10-16 09:49
The creator of Quill.JS gave us a solution:

https://github.com/quilljs/quill/issues/1753#issuecomment-336791018

**Comment by Natim** [comment] 2017-10-20 16:08
@cedricium do you have any idea how I can detect the indent level Jason Chen is talking about in the comment below?

**Comment by cedricium** [comment] 2017-10-20 16:20
I'm not sure. First thought would be that `context` is an Object that would have the `indent` format specified (as well as the indent level).

Or by "check indent level" he might mean manually getting the format using `quill.getFormat()` (https://quilljs.com/docs/api/#getformat) which would give you the indent level if the `indent` format is active for the given `range`.

**Closed** 2018-01-09 13:51 UTC
Labels: QuillJS Bug, ckeditor

**Comment by SoftVision-EmilPasca** [comment] 2018-01-09 15:19
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.
