### ISSUE TITLE
Flash issue

### ISSUE THREAD

**Issue by marniepw** [mozilla/notes#667] opened 2018-02-05 23:45 UTC
[Description]: When I play flash games and open the Firefox Notes the screen of the game becomes black until I close Notes.

[Affected versions]: Unknown; from January survey feedback.

[Prerequisites]:

[Steps to reproduce]: 

[Expected result]:

[Actual result]:

[Additional Notes]: Can't repro w/ duke dashing (ryanfeeley)

**Comment by Natim** [comment] 2018-02-07 13:07
We couldn't reproduce this, I am going to close it.

**Closed by Natim** 2018-02-07 13:07 UTC
