### ISSUE TITLE
'scripts' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Sudeepa14** [mozilla/notes#200] opened 2017-08-13 06:36 UTC
## 'npm install' returns " 'scripts' is not recognized as an internal or external command," on **windows**

`
` >notes@1.6.3-dev postinstall D:\mypath\notes
  > scripts/postinstall.sh
"scripts" is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notes@1.6.3-dev postinstall: `scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the notes@1.6.3-dev postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:``

**Comment by pdehaan** [comment] 2017-08-13 16:33
@Sudeepa14 Are you using Cygwin or Powershell on Windows, or just cmd.exe?
Also, what version of Windows are you using?

**Comment by Sudeepa14** [comment] 2017-08-14 04:16
hi @pdehaan , thanks for the response, it is Windows 10. I used CMD at the first place. Then got to know 
about Cygwin. But still no go. Same outcome. I executed each command in the postinstall.sh (starting with 'CP') manually.  Not like CMD ,Cygwing was able to execute them. I was able to run the project on Ubuntu 16.04 LTS perfectly.  If there are special requirements, shouldn't they be included in the doc?

**Comment by pdehaan** [comment] 2017-08-14 04:23
> If there are special requirements, shouldn't they be included in the doc?

They should, yes. I'll try taking a look and see if I can find a way to run shell scripts on Mac/Linux and Windows. Maybe we just need to include a .bat file for Windows and developers will have to run that manually for now, until we can find a good cross-platform solution.

**Comment by Sudeepa14** [comment] 2017-08-14 05:16
> Even better, maybe we just refactor these 4 cp commands into a cross-platform Node script.
Will that solve 'script not found' ? Currently I'm comfortable with going with Ubuntu and I would like to contribute to the #198 . How can I allocate myself to the future-request ?

**Comment by pdehaan** [comment] 2017-08-14 06:05
@Sudeepa14 I have a PR for this issue at #202.

**Comment by pdehaan** [comment] 2017-08-14 06:08
As for issue #198, I'd just comment in that bug and ask if it's free/OK to work on. I was uncertain from the latest comment if it was a bug, or working as intended.

Thanks for all your help!

**Comment by Sudeepa14** [comment] 2017-08-14 06:39
@pdehaan  Thanks for the advice and for the fix I'll try the fixed with windows ;)

**Comment by johngruen** [comment] 2017-08-14 15:09
Fixed by #202, @vladikoff will comment

**Closed** 2017-08-17 13:45 UTC
