### ISSUE TITLE
[Android] Notes 1.1 now crashes on Lolipop 5.1.1

### ISSUE THREAD

**Issue by Mozinet-fr** [mozilla/notes#1357] opened 2018-08-24 15:25 UTC
### [Description]:
I updated Notes to 1.1 version. On my tablet and phone both on Android 5.1.1, the Notes app crashes. Before log in was impossible.

### [Affected versions]:
Notes 1.1 on Android 5.1.1

### [Steps to reproduce]:
Update to 1.1, open the Notes app and tap on login.

### [Expected result]:

Having a login screen.

### [Actual result]:
"Notes" has stopped.

**Comment by Softvision-RemusDranca** [comment] 2018-08-24 15:41
Hi, @Mozinet-fr, thank you for reporting this, however is a dupe off #1344. Currently Notes does not support Android versions < 6.

**Comment by vladikoff** [comment] 2018-08-24 15:43
We have a fix in the works that should address this in the future version, @Mozinet-fr. It's going into testing soon

**Comment by Mozinet-fr** [comment] 2018-08-24 15:48
You could have warned at least.

**Closed** 2023-01-06 11:55 UTC
Labels: ARCHIVED
