### ISSUE TITLE
You cannot add "blank space" characters at the end of a paragraph after enabling/disabling a text style option

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#416] opened 2017-11-21 10:43 UTC
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b2 build with CKeditor) installed.
- Have a paragraph in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Move the text caret at the end of the paragraph.
3. Click a text style option from the sidebar's toolbar.
4. Press the "Space" key and observe the behavior.

**[Expected result]:**
- The "blank space" character is added. 

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- The issue is not reproducible with the Bulleted/Numbered lists.
- The issue is not reproducible with any other keys.
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33068303-7a452efa-ceb9-11e7-8ee1-0a8a35d432c8.gif)

**Comment by vladikoff** [comment] 2017-11-23 16:17
CKeditor expects a character not space after selected bold. We should try to make this work like Word or other text editors...

![image](https://user-images.githubusercontent.com/128755/33181877-c70687d4-d03f-11e7-8962-c44eebafd090.png)

**Comment by vladikoff** [comment] 2017-11-25 21:34
@reinmar @szymonkups Any idea of what could be going on here? I cannot reproduce the same issue here: https://ckeditor5.github.io/

**Comment by Mgsy** [comment] 2017-11-27 09:24
@vladikoff, I was able to reproduce your bug (even in https://ckeditor5.github.io/) , so I've created new issue in our CKEditor 5 repository - https://github.com/ckeditor/ckeditor5/issues/692.

**Comment by vladikoff** [comment] 2017-11-27 17:26
@Mgsy thanks so much!!! 👍

**Comment by Mgsy** [comment] 2018-03-08 07:18
@vladikoff, fix to this issue has landed on the latest master.

**Comment by vladikoff** [comment] 2018-03-08 11:41
@Mgsy hurrah!!!! Thank you!

**Closed** 2018-06-13 23:49 UTC
Labels: ckeditor

**Comment by Softvision-MariusComan** [comment] 2018-06-18 07:51
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 18.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
