### ISSUE TITLE
[Android] The "Synced" status message wrongly remains displayed in the note view

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1005] opened 2018-04-26 15:07 UTC
**[Affected Platforms]:**
- Samsung Galaxy S7 edge (Android 7.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v1938) installed.
- Have at list one note created.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap on any note and modify the content.
3. Observe the top part of the note.

**[Expected result]:**
- After the content is synced, the "Synced" message is displayed and disappears after ~2 seconds.

**[Actual result]:**
- After the content is synced, the "Synced" message remains displayed.

**[Notes]:**
- The "Synced" message is also displayed right after a new note was created.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/39314288-95d9e258-497c-11e8-9503-517a489e94bc.gif)

**Comment by sebastienbarbier** [comment] 2018-04-27 03:30
This behaviour is defined **by design**, and give the user a feedback about current status.

@vladikoff should we think about an an **alternative** ? 
@Softvision-MariusComan You think this is **too intrusive** and should be implemented differently (like displaying title after few seconds instead) ?

**Comment by vladikoff** [comment] 2018-04-27 03:43
@antlam ideas?

**Comment by matijakovacevic** [comment] 2018-04-27 10:39
sry, where can I find the android app ?
thank you

**Comment by Softvision-MariusComan** [comment] 2018-04-27 13:55
@sebastienbarbier I've logged this issue according the mock-ups from: https://mozilla.invisionapp.com/share/BTGS26C2FE4#/screens/290379304. In the mock-ups the status message disappears after few seconds. 
However, I think that it will be a good improvement if the status message would disappear after few seconds and the title be displayed instead.

**Comment by antlam** [comment] 2018-04-27 19:09
@vladikoff sorry! I must've not communicated this well. 

Could we do a 250ms fade out after a 500ms delay once the status hits "Synced"?

Syncing... > Synced > 500ms > 250ms fade to 0% opacity.

**Comment by sebastienbarbier** [comment] 2018-05-16 08:00
This has been fixed with PR #1046

**Closed by sebastienbarbier** 2018-05-16 08:00 UTC
Labels: [QA]:Minor issue, mobile 📱

**Comment by Softvision-MariusComan** [comment] 2018-05-16 11:32
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2184) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
