### ISSUE TITLE
[Android] The content is not actually synced when you swipe down the list view

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#991] opened 2018-04-25 14:31 UTC
**[Affected Platforms]:**
- Samsung Galaxy S7 edge (Android 7.0)

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.1.0dev custom built on 25.04.2018) installed.
- Have the latest version of the "Firefox Notes" application (1.0alpha1) installed.
- Have Firefox Notes opened in the browser and also on the mobile device.
- Have at least one note created.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click any note and modify the displayed content.
3. Open the Notes application and log in if needed.
4. Swipe down.
5. Tap the note modified on desktop and observe the behavior.

**[Expected result]:**
- The edits made on desktop are synchronized with the app.

**[Actual result]:**
- The "Notes synced!" message is displayed in the bottom of the application, but the content is not actually synced.

**[Additional Notes]:**
- The issue is not reproducible if the sync action is made from the side menu.
- Attached a screen recording of the issue:
![rec of the issue 1](https://user-images.githubusercontent.com/31243259/39252506-7a489e36-48ae-11e8-926d-136ccd97261a.gif)

**Comment by sebastienbarbier** [comment] 2018-04-27 04:54
Could not reproduce, I assume it has been fixed by #986.

**Closed by sebastienbarbier** 2018-04-27 04:54 UTC
Labels: [QA]:Normal issue, mobile 📱

**Comment by Softvision-MariusComan** [comment] 2018-04-27 12:27
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v1964) installed. Verified on on Samsung S7 Edge(Android 7.0).
