### ISSUE TITLE
Keyboard shortcut issues/not working

### ISSUE THREAD

**Issue by marniepw** [mozilla/notes#668] opened 2018-02-05 23:50 UTC
[Description]:

1. Cannot Ctrl/Cmd + Z... Cannot undo accidental deletion.
2. Ctrl+C, Ctrl+X, and Ctrl+V are completely broken today.

[Affected versions]: Unknown; from January survey feedback.

[Prerequisites]:

[Steps to reproduce]:

[Expected result]:

[Actual result]:

[Additional Notes]:

**Comment by Natim** [comment] 2018-02-07 13:06
I can't reproduce this:
- Ctrl+C, Ctrl+X, and Ctrl+V are completely broken today.

This is a duplicate of #472 bug because of a missing Firefox event handling.

- Cannot Ctrl/Cmd + Z... Cannot undo accidental deletion.

**Closed by Natim** 2018-02-07 13:06 UTC
