### ISSUE TITLE
When hovering the "Synced at.." text, the Sync email is no longer displayed after switching sidebars

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#629] opened 2018-01-30 10:55 UTC
[Affected versions]:
- Firefox 58.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 2018-01-30) installed.
- Be logged in a Firefox Notes account.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Switch the "Notes" sidebar to another one, eg. "History".
3. Switch back to the "Notes" sidebar.
4. Hover over the "Synced at.." text and observe the behavior.

[Expected result]:
- A tooltip with the Sync email is displayed.

[Actual result]:
- No tooltip is displayed.

[Notes]:
- This issue is also reproducible if you restart the browser, without switching the sidebars.
- This issue is reproducible with Firefox Notes from Test Pilot experiments [page](https://github.com/mozilla/notes/issues).
- Here is a screen recording of the issue:
![display the email address](https://user-images.githubusercontent.com/31244235/35562630-a2065574-05bc-11e8-8e36-e2b4f9e6e736.gif)

**Comment by himanish-star** [comment] 2018-01-31 01:48
@Natim, shall I try to fix this ?

**Comment by vladikoff** [comment] 2018-01-31 02:04
@himanish-star sure, I think you need to cache the email somewhere after the user authenticates

**Comment by himanish-star** [comment] 2018-01-31 03:01
Sure, I'll start looking into this

**Comment by vladikoff** [comment] 2018-01-31 15:32
Should be fixed via https://github.com/mozilla/notes/pull/637

**Closed by vladikoff** 2018-01-31 15:32 UTC

**Comment by Softvision-CristinaBadescu** [comment] 2018-02-01 09:28
This issue is no longer reproducible using latest Firefox Notes version 2.2.0 dev (custom built 2018-02-01), on latest Nightly build 60.0a1 (2018-01-31), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.

However, I've noticed that the text from the tooltip is different: before it displayed only the Sync email address, and now it displays "Sync with [e-mail address]", as you can see in the below screenshot. Should I log a new issue for this?
![sync with](https://user-images.githubusercontent.com/31244235/35671050-e8aee6ee-0742-11e8-8a19-44176c3b0e16.png)

**Comment by Natim** [comment] 2018-02-01 09:34
It is not a bug it is actually a feature made in #639
