### ISSUE TITLE
Correct save and sync language

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#598] opened 2018-01-18 16:32 UTC
STEPS TO REPRODUCE
1. Enable Syncing of Notes
2. Edit a note

EXPECTED RESULTS
* After a note has been edited, footer should say "Syncing…"
* Before a note has been edited it shoudl say "Last Synced HH:MM"

ACTUAL RESULTS
* It does this but also has Save and Saving…

**Comment by Natim** [comment] 2018-01-18 16:33
Duplicate of #597

**Closed** 2018-01-18 16:34 UTC
