### ISSUE TITLE
The content is wrongly duplicated after signing in into "Notes" if more then one browser window is opened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#778] opened 2018-03-16 14:03 UTC
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0rc3) installed.
- Have content in the "Firefox Notes" sidebar.
- Have valid FxA credentials.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and open a new window.
2. Click the "Sync Your Notes" button from the bottom-right part of the sidebar.
3. Enter the credentials from prerequisites and press the "Sign In" button.
4. Observe the sidebar's displayed content.

**[Expected result]:**
- The content from prerequisites remains unchanged after the sync action.

**[Actual result]:**
- The content from prerequisites is duplicated.

**[Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37524741-6a0c2f46-2933-11e8-823d-c97c7b218795.gif)

**Comment by sebastienbarbier** [comment] 2018-03-19 02:25
I have the same issue in v4, might come from sync.js so I'll investigate on this should no be difficult 👍

**Comment by sebastienbarbier** [comment] 2018-03-21 05:50
Should be fixed in #743 with 4.0.0-beta1.

**Comment by sebastienbarbier** [comment] 2018-03-26 05:35
Could not reproduce on master. I believe v4 fix this.

**Closed by sebastienbarbier** 2018-03-26 05:35 UTC
