### ISSUE TITLE
[User Feedback] 9000 lines break CKEditor

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#541] opened 2018-01-03 20:44 UTC
> 9000 lines break ckeditor script. Every single action, even a copy (ctrl+c or via the contextual menu) freezes the browser for at least 1 or 2 minutes. In 2017 we shall have better editor (even with markdown support) than the ol’ goo’ fellow named ckeditor.

**Comment by vladikoff** [comment] 2018-01-04 16:57
@Mgsy Have you seen this happen in your CKEditor testing?

**Comment by Mgsy** [comment] 2018-01-05 11:40
> @Mgsy Have you seen this happen in your CKEditor testing?

Hey, @vladikoff. Basically, behaviour of the editor depends on what do you mean by saying `9000 lines`. Is it 9000 lines divided to paragraphs? Or 9000 lines contained in one paragraph? 

In the first case, the editor doesn't freeze, unless you perform some operation on whole content (but it's still not 1-2 minutes). I was able to edit my text in the editor with 10 000 lines without any problems.

Second case is problematic, not only for the editor, but also for the browser and, to be honest, having  9000 lines of text in one paragraph is an edge case. Indeed, in this situation we experience freezes, long time of executing editor's commands etc. 

Please, keep in mind that we're in the alpha phase and the performance improvement is not our goal at the moment. We'll take care of it after we stabilize other things.

**Comment by Natim** [comment] 2018-01-23 14:55
Duplicate of #546

**Closed by Natim** 2018-01-23 14:55 UTC
Labels: Shield
