### ISSUE TITLE
Disable context menu everywhere except the notepad itself

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#774] opened 2018-03-15 15:27 UTC
### [Description]:

Disable context menu everywhere except the notepad itself

**Comment by vladikoff** [comment] 2018-03-15 15:51
Also disable the context menu in the menu: 

![](http://v14d.com/a/5aaa968087ad8.gif)

cc @Softvision-MariusComan

**Comment by Softvision-MariusComan** [comment] 2018-03-15 17:18
I have managed to reproduce this issue on different OS's with the bellow STR .
However since I'm not sure if this issue should be fixed on "Notes" side or on the "Firefox" side, I've also logged this issue on Bugzilla: [Bug 1446031](https://bugzilla.mozilla.org/show_bug.cgi?id=1446031)

**[Affected versions]:**
- Firefox Nightly 61.0a1 Build ID 20180315100042

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0rc3) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button.
3. Log in into "Firefox Notes" or create a new account.
4. Close and reopen the sidebar.
5. Right click in the bottom toolbar and observe the behavior.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- A context menu is opened.

**[Regression window]:**
Considering that I have not managed to reproduce this issue on older Nightly builds (eg. the build from 2018-03-01 ), using the Mozregression tools I have found a regression window:

Last good revision: c842abb7cfbf39e0c1cfb9a1f3a1d6415cd10744
First bad revision: 84ea422093dd615bd191a3e579ed299d96c802f1
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=c842abb7cfbf39e0c1cfb9a1f3a1d6415cd10744&tochange=84ea422093dd615bd191a3e579ed299d96c802f1

**[Additional Notes]:**
- The issue is reproducible if the sidebar is switched instead.
- This issue is still reproducible after browser restart.
- The issue is still reproducible after logging out from "Firefox Notes"
- This issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37479566-a1d74752-2885-11e8-9899-63e74f4237b1.gif)

**Closed** 2018-03-28 02:04 UTC
