### ISSUE TITLE
The "Disable sync" option is wrongly displayed in the "Notes" menu even if you are not logged into "Firefox Notes"

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#483] opened 2017-12-06 14:00 UTC
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b8) installed.
- You must not be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button and switch back to the first window.
3. Click the "Notes" menu from the bottom right part of the sidebar and observe the displayed options.

**[Expected result]:**
- The "Give Feedback" option is displayed.

**[Actual result]:**
- The "Give Feedback" and the "Disable sync" options are displayed. 

**[Notes]:**
- The "Status bar" color remains "Orange" even after the sidebar is focused, you paste content or you are writing something into it.
- If the log in window is closed before logging in, then the "Reconnect to Sync" message is wrongly displayed in the "Status bar".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33665091-6b8aa318-da9e-11e7-8adc-10ef2018c9f1.gif)

**Comment by vladikoff** [comment] 2017-12-06 23:41
The "Saved at" indicator in "yellow" is fixed in https://github.com/mozilla/notes/pull/425/commits/cbc878d0cdb5f75d63425ee3b7fa29a17448720c

> The "Give Feedback" and the "Disable sync" options are displayed.

That's by design.

 However I'm gonna keep this bug open because we might be able to improve the "Verify Account" / "Reconnect Sync" flow **on login**.

**Comment by Natim** [comment] 2018-02-02 13:54
I believe this has been fixed.

**Closed by Natim** 2018-02-02 13:54 UTC
Labels: enhancement
