### ISSUE TITLE
New line / Return characters are removed when pasting ASCII text into notes

### ISSUE THREAD

**Issue by kekkc** [mozilla/notes#937] opened 2018-04-15 01:14 UTC
### [Description]:
New line / Return characters are removed when pasting ASCII text into notes

### [Affected versions]:
Notes 4.0.0

### [Steps to reproduce]:
Try to paste this text into notes:
first line

third line

### [Expected result]:
first line

third line

### [Actual result]:
first line
third line

**Comment by SoftVision-EmilPasca** [comment] 2018-04-16 15:29
Thanks @kekkc for reporting this issue. However, this is a duplicate of https://github.com/mozilla/notes/issues/677.

**Closed by SoftVision-EmilPasca** 2018-04-16 15:29 UTC
